### ISSUE TITLE
Remove referenced components after dereferencing

### ISSUE THREAD

**Issue by RemiBardon** [anttiviljami/openapicmd#14]
After a `openapi read ./foo.json -f json -D > bar.json`, `parameters`, `schemas`, `requestBodies`, `responses` and `examples` are still present in `components`. They are useless, since they have been dereferenced.

I dereferenced a 1500 lines file, and it gave me 9700 lines. After removing useless components, I went back to 4000 lines (which is a lot better).

**Comment by anttiviljami** [comment]
The dereferencing is done by `@apidevtools/swagger-parser`. Closing :)
