### ISSUE TITLE
Issue generating types remotely using Node v20

### ISSUE THREAD

**Issue by kiikka** [anttiviljami/openapicmd#62]
Hello!

I'm having an issue with generating types remotely using Node v20. 

I've been running the following command.

`openapi typegen http://localhost:8080/o/openapi-rest/v1.0/openapi.yaml > ./openapi.d.ts -H "Authorization: Basic xxxx"`

This used to work still with Node v16, but after upgrading to v20 I get the following error.

`ResolverError: Error downloading xxx
socket hang up
    at /node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js:127:16`

Is there a need to modify my command or is it possible that the above mentioned library is deprecated for Node v20?

- Aleksi

**Comment by anttiviljami** [comment]
Very possible. Try upgrading it and see if it fixes the issue

**Comment by kiikka** [comment]
I mean the library seems to be under openapicmd or the axios version should be updated

**Comment by anttiviljami** [comment]
openapicmd is free and open source :) please execute ✅

**Comment by kiikka** [comment]
I looked into this and it seems like the issue might be a dependencys dependency...

https://github.com/APIDevTools/swagger-parser/pull/256

**Comment by anttiviljami** [comment]
Nice job! 💪

**Comment by kiikka** [comment]
After a bit of testing it turns out it is possibly an issue with Node v20 instead. I don't really know if its some setting that is required for it to work or should the http request in json-schema-ref-parser need to be adjusted for it to work. 

Node v16 and Node v18 works still.

**Comment by kiikka** [comment]
This ended up being a Node v20 / platform issue on our end.

For people interested: we are generating types from a local API and the URL to the API is along the lines of `thing.local:8080/api` where thing.local is mapped to 127.0.0.1.

This URL worked previously (Node v16) but after switching to Node v20 we had to change the URL for the command from
`thing.local:8080/api ` to `localhost:8080/api `(127.0.0.1 worked as well).

I'm not sure if it's possible to add some host option to the command that would be set for the created connection to get the "custom" host work locally.

**Comment by kiikka** [comment]
Case closed
